### ISSUE TITLE
psutil.ZombieProcess process still exists but it's a zombie

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/mine#81]
This seems to have started happening after the macOS High Sierra update:

```
Traceback (most recent call last):
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 313, in catch_zombie
    yield
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Browning/.pyenv/versions/3.6.1/bin/mine", line 11, in <module>
    sys.exit(main())
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/mine/cli.py", line 89, in main
    success = run(path=args.file, **kwargs)
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/mine/cli.py", line 123, in run
    if not manager.is_running(services.APPLICATION):
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/mine/manager.py", line 29, in wrapped
    running = func(self, application)
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/mine/manager.py", line 176, in is_running
    process = self._get_process(name)
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/mine/manager.py", line 104, in _get_process
    command = ' '.join(process.cmdline()).lower()
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/__init__.py", line 712, in cmdline
    return self._proc.cmdline()
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 295, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/Browning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 324, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=19446)
```

**Comment by jacebrowning** [comment]
I haven't seen this in a while.
